name: chap04_material_flutter_app
description: 4장 실습

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - image/flutter.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: font/Pacifico-Regular.ttf
          weight: 400
